version: '2'
services:
  datastore:
    volumes:
      - $HOME/.opam:$HOME/.opam
    build:
      context: ./datastore
  monkey_ocaml:
    build:
      context: .
    volumes:
      - .:/monkey_ocaml
    volumes_from:
      - datastore
